from flask import Flask, jsonify, request
from flask_cors import CORS

from tools import (
    load_citypulse_data,
    investigate_zone,
    compare_zones,
    get_event_timeline,
    get_evidence,
    get_recovery_status
)

from agent import CivicAIAgent
from civic_brief import generate_civic_brief
from simulation import simulate_zone_change


# ============================================================
# CITYPULSE FLASK SERVER
# ============================================================

app = Flask(__name__)

# Allow the frontend running on Live Server to access Flask
CORS(app)

# Initialize Civic AI Agent
agent = CivicAIAgent()


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_all_zones():
    """
    Load the latest CityPulse intelligence generated by Member 1.
    """
    result = load_citypulse_data()

    if not result.get("success"):
        return None, result.get(
            "error",
            "Unable to load CityPulse intelligence."
        )

    return result.get("data", []), None


def find_zone(zone_id):
    """
    Find one zone from the latest CityPulse intelligence.
    """
    zones, error = get_all_zones()

    if error:
        return None, error

    for zone in zones:
        if zone.get("zone_id") == zone_id:
            return zone, None

    return None, f"Zone {zone_id} was not found."


def calculate_city_status(risk_score):
    """
    Convert city risk score into the CityPulse status.
    """

    if risk_score >= 75:
        return "CRITICAL"

    if risk_score >= 50:
        return "EMERGING"

    if risk_score >= 30:
        return "WATCH"

    return "NORMAL"


# ============================================================
# HOME
# ============================================================

@app.route("/", methods=["GET"])
def home():

    return jsonify({
        "success": True,
        "message": "CityPulse API is running.",
        "service": "CityPulse Civic Intelligence Command Center"
    })


# ============================================================
# MAIN CITYPULSE API
# ============================================================

@app.route("/api/citypulse", methods=["GET"])
def citypulse():

    zones, error = get_all_zones()

    if error:
        return jsonify({
            "success": False,
            "error": error
        }), 500

    # --------------------------------------------------------
    # CITY RISK
    # --------------------------------------------------------

    risk_scores = [
        zone.get("risk_score", 0)
        for zone in zones
    ]

    city_risk_score = max(risk_scores) if risk_scores else 0

    city_status = calculate_city_status(
        city_risk_score
    )

    # --------------------------------------------------------
    # ZONE INTELLIGENCE
    # --------------------------------------------------------

    zone_outputs = []

    for zone in zones:

        zone_id = zone.get("zone_id")

        investigation = agent.investigate(
            zone_id
        )

        zone_outputs.append({

            "zone_id": zone_id,

            "status": zone.get(
                "status",
                "NORMAL"
            ),

            "risk_score": zone.get(
                "risk_score",
                0
            ),

            "signals_detected": zone.get(
                "signals_detected",
                []
            ),

            "investigation": investigation
        })

    # --------------------------------------------------------
    # PRIORITY ZONE
    # --------------------------------------------------------

    priority_zone = None

    if zones:

        priority_zone = max(
            zones,
            key=lambda z: z.get(
                "risk_score",
                0
            )
        )

    # --------------------------------------------------------
    # CIVIC BRIEF
    # --------------------------------------------------------

    civic_brief = None

    if priority_zone:

        priority_zone_id = priority_zone.get(
            "zone_id"
        )

        explanation = agent.explain(
            priority_zone_id
        )

        brief_result = generate_civic_brief(
            explanation
        )

        if brief_result.get("success"):

            civic_brief = brief_result.get(
                "brief"
            )

        else:

            civic_brief = (
                "Unable to generate civic brief."
            )

    # --------------------------------------------------------
    # RESPONSE
    # --------------------------------------------------------

    return jsonify({

        "success": True,

        "city_status": city_status,

        "city_risk_score": city_risk_score,

        "priority_zone": (
            priority_zone.get("zone_id")
            if priority_zone
            else None
        ),

        "zones": zone_outputs,

        "civic_brief": civic_brief

    })


# ============================================================
# AI INVESTIGATION — INVESTIGATE
# ============================================================

@app.route(
    "/api/agent/investigate",
    methods=["GET"]
)
def agent_investigate():

    zone_id = request.args.get(
        "zone_id",
        "ZONE_A"
    )

    result = agent.investigate(
        zone_id
    )

    return jsonify({
        "success": True,
        "agent_action": "INVESTIGATE",
        "zone_id": zone_id,
        "result": result
    })


# ============================================================
# AI INVESTIGATION — EXPLAIN
# ============================================================

@app.route(
    "/api/agent/explain",
    methods=["GET"]
)
def agent_explain():

    zone_id = request.args.get(
        "zone_id",
        "ZONE_A"
    )

    result = agent.explain(
        zone_id
    )

    return jsonify({
        "success": True,
        "agent_action": "EXPLAIN",
        "zone_id": zone_id,
        "result": result
    })


# ============================================================
# AI INVESTIGATION — VERIFY
# ============================================================

@app.route(
    "/api/agent/verify",
    methods=["GET"]
)
def agent_verify():

    zone_id = request.args.get(
        "zone_id",
        "ZONE_A"
    )

    result = agent.verify(
        zone_id
    )

    return jsonify({
        "success": True,
        "agent_action": "VERIFY",
        "zone_id": zone_id,
        "result": result
    })


# ============================================================
# AI INVESTIGATION — COMPARE
# ============================================================

@app.route(
    "/api/agent/compare",
    methods=["GET"]
)
def agent_compare():

    zone_1 = request.args.get(
        "zone_1",
        "ZONE_A"
    )

    zone_2 = request.args.get(
        "zone_2",
        "ZONE_B"
    )

    result = agent.compare(
        zone_1,
        zone_2
    )

    return jsonify({
        "success": True,
        "agent_action": "COMPARE",
        "zone_1": zone_1,
        "zone_2": zone_2,
        "result": result
    })


# ============================================================
# AI INVESTIGATION — QUESTION
# ============================================================

@app.route(
    "/api/agent/question",
    methods=["POST"]
)
def agent_question():

    data = request.get_json(
        silent=True
    ) or {}

    zone_id = data.get(
        "zone_id",
        "ZONE_A"
    )

    question = str(
        data.get(
            "question",
            ""
        )
    ).strip()

    if not question:

        return jsonify({
            "success": False,
            "error": "Question is required."
        }), 400

    # --------------------------------------------------------
    # Load structured evidence
    # --------------------------------------------------------

    investigation = agent.investigate(
        zone_id
    )

    evidence = agent.verify(
        zone_id
    )

    timeline = get_event_timeline(
        zone_id
    )

    recovery = get_recovery_status(
        zone_id
    )

    # --------------------------------------------------------
    # Simple intent detection
    # --------------------------------------------------------

    question_lower = question.lower()

    answer = ""

    if (
        "start" in question_lower
        or "when" in question_lower
    ):

        start = (
            timeline
            .get("event_start")
            if isinstance(
                timeline,
                dict
            )
            else None
        )

        if start:

            answer = (
                f"The reconstructed event in "
                f"{zone_id.replace('_', ' ')} "
                f"starts at approximately "
                f"+{start.get('time_offset_minutes', '—')} "
                f"minutes."
            )

        else:

            answer = (
                "No confirmed event start "
                "was found in the available "
                "reconstructed timeline."
            )

    elif (
        "signal" in question_lower
        or "what changed" in question_lower
    ):

        signals = investigation.get(
            "signals_detected",
            []
        )

        answer = (
            "The detected signals are: "
            + (
                ", ".join(signals)
                if signals
                else "none"
            )
            + "."
        )

    elif (
        "stage" in question_lower
        or "lifecycle" in question_lower
    ):

        lifecycle = (
            recovery.get(
                "lifecycle_stage"
            )
            or investigation.get(
                "event_lifecycle",
                {}
            ).get(
                "lifecycle_stage"
            )
            or "MONITORING"
        )

        answer = (
            f"The current event lifecycle "
            f"stage is {lifecycle.replace('_', ' ')}."
        )

    elif (
        "risk" in question_lower
        or "flag" in question_lower
        or "why" in question_lower
    ):

        answer = (
            f"{zone_id.replace('_', ' ')} "
            f"has a risk score of "
            f"{investigation.get('risk_score', 0)}. "
            f"{evidence.get('reason', '')}"
        )

    else:

        answer = (
            "Based on the current structured "
            "CityPulse evidence, the system has "
            f"identified {len(investigation.get('signals_detected', []))} "
            "active civic signals in "
            f"{zone_id.replace('_', ' ')}. "
            "The evidence should be interpreted "
            "as observed associations rather "
            "than confirmed causation."
        )

    return jsonify({

        "success": True,

        "agent_action": "QUESTION",

        "zone_id": zone_id,

        "question": question,

        "answer": answer,

        "evidence": evidence,

        "investigation": investigation,

        "timeline": timeline,

        "recovery": recovery

    })


# ============================================================
# WHAT-IF SIMULATION
# ============================================================

@app.route(
    "/api/simulation",
    methods=["POST"]
)
def simulation():

    data = request.get_json(
        silent=True
    ) or {}

    zone_id = data.get(
        "zone_id",
        "ZONE_A"
    )

    signal = data.get(
        "signal",
        "rainfall_mm"
    )

    percentage_change = data.get(
        "percentage_change",
        0
    )

    # --------------------------------------------------------
    # Validate percentage
    # --------------------------------------------------------

    try:

        percentage_change = float(
            percentage_change
        )

    except (
        TypeError,
        ValueError
    ):

        return jsonify({
            "success": False,
            "error": (
                "percentage_change must "
                "be a number."
            )
        }), 400

    # --------------------------------------------------------
    # Run actual Member 2 simulation engine
    # --------------------------------------------------------

    try:

        result = simulate_zone_change(
            zone_id,
            signal,
            percentage_change
        )

    except Exception as error:

        return jsonify({

            "success": False,

            "error": str(error)

        }), 500

    return jsonify({

        "success": True,

        "agent_action": "SIMULATE",

        "result": result

    })


# ============================================================
# EVENT TIMELINE
# ============================================================

@app.route(
    "/api/event/timeline",
    methods=["GET"]
)
def event_timeline():

    zone_id = request.args.get(
        "zone_id",
        "ZONE_A"
    )

    result = get_event_timeline(
        zone_id
    )

    return jsonify({

        "success": True,

        "zone_id": zone_id,

        "timeline": result

    })


# ============================================================
# EVIDENCE
# ============================================================

@app.route(
    "/api/event/evidence",
    methods=["GET"]
)
def event_evidence():

    zone_id = request.args.get(
        "zone_id",
        "ZONE_A"
    )

    result = get_evidence(
        zone_id
    )

    return jsonify({

        "success": True,

        "zone_id": zone_id,

        "evidence": result

    })


# ============================================================
# RECOVERY
# ============================================================

@app.route(
    "/api/event/recovery",
    methods=["GET"]
)
def event_recovery():

    zone_id = request.args.get(
        "zone_id",
        "ZONE_A"
    )

    result = get_recovery_status(
        zone_id
    )

    return jsonify({

        "success": True,

        "zone_id": zone_id,

        "recovery": result

    })


# ============================================================
# SERVER START
# ============================================================

if __name__ == "__main__":

    print()
    print("=" * 65)
    print("CITYPULSE CIVIC INTELLIGENCE API")
    print("=" * 65)
    print()
    print("Server starting...")
    print()
    print("Main API:")
    print(
        "http://localhost:5000/api/citypulse"
    )
    print()
    print("Agent API:")
    print(
        "http://localhost:5000/api/agent/investigate"
    )
    print()
    print("Simulation API:")
    print(
        "http://localhost:5000/api/simulation"
    )
    print()
    print("Press CTRL+C to stop the server.")
    print()

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )