import json
import os


OUTPUT_FILE = os.path.join(
    os.path.dirname(__file__),
    "citypulse_output.json"
)


def load_citypulse_data():
    """
    Load the latest intelligence output generated by Member 1.
    """

    if not os.path.exists(OUTPUT_FILE):
        return {
            "success": False,
            "error": "citypulse_output.json not found."
        }

    try:
        with open(OUTPUT_FILE, "r", encoding="utf-8") as file:
            data = json.load(file)

        return {
            "success": True,
            "data": data
        }

    except json.JSONDecodeError:
        return {
            "success": False,
            "error": "citypulse_output.json contains invalid JSON."
        }

    except Exception as error:
        return {
            "success": False,
            "error": str(error)
        }


def investigate_zone(zone_id):
    """
    Return intelligence for a specific zone.
    """

    result = load_citypulse_data()

    if not result["success"]:
        return result

    city_data = result["data"]

    for zone in city_data:
        if zone.get("zone_id") == zone_id:
            return {
                "success": True,
                "zone": zone
            }

    return {
        "success": False,
        "error": f"{zone_id} not found."
    }


def compare_zones(zone_id_1, zone_id_2):
    """
    Compare the intelligence of two zones.
    """

    result = load_citypulse_data()

    if not result["success"]:
        return result

    city_data = result["data"]

    zone_1 = None
    zone_2 = None

    for zone in city_data:

        if zone.get("zone_id") == zone_id_1:
            zone_1 = zone

        if zone.get("zone_id") == zone_id_2:
            zone_2 = zone

    if zone_1 is None:
        return {
            "success": False,
            "error": f"{zone_id_1} not found."
        }

    if zone_2 is None:
        return {
            "success": False,
            "error": f"{zone_id_2} not found."
        }

    return {
        "success": True,
        "comparison": {
            "zone_1": {
                "zone_id": zone_1["zone_id"],
                "status": zone_1["status"],
                "risk_score": zone_1["risk_score"],
                "signals_detected": zone_1["signals_detected"]
            },
            "zone_2": {
                "zone_id": zone_2["zone_id"],
                "status": zone_2["status"],
                "risk_score": zone_2["risk_score"],
                "signals_detected": zone_2["signals_detected"]
            }
        }
    }


def get_event_timeline(zone_id):
    """
    Return the detected event timeline for a specific zone.
    """

    result = load_citypulse_data()

    if not result["success"]:
        return result

    city_data = result["data"]

    for zone in city_data:

        if zone.get("zone_id") == zone_id:

            event = zone.get("event", {})

            return {
                "success": True,
                "zone_id": zone_id,
                "event": event
            }

    return {
        "success": False,
        "error": f"{zone_id} not found."
    }


def get_evidence(zone_id):
    """
    Return the evidence explaining why a zone was flagged.
    """

    result = load_citypulse_data()

    if not result["success"]:
        return result

    city_data = result["data"]

    for zone in city_data:

        if zone.get("zone_id") == zone_id:

            why_flagged = zone.get(
                "why_flagged",
                {}
            )

            return {
                "success": True,
                "zone_id": zone_id,
                "evidence": why_flagged
            }

    return {
        "success": False,
        "error": f"{zone_id} not found."
    }


def get_recovery_status(zone_id):
    """
    Return recovery and lifecycle information for a zone.
    """

    result = load_citypulse_data()

    if not result["success"]:
        return result

    city_data = result["data"]

    for zone in city_data:

        if zone.get("zone_id") == zone_id:

            recovery = zone.get(
                "recovery",
                {}
            )

            lifecycle = zone.get(
                "event_lifecycle",
                {}
            )

            return {
                "success": True,
                "zone_id": zone_id,
                "recovery": recovery,
                "event_lifecycle": lifecycle
            }

    return {
        "success": False,
        "error": f"{zone_id} not found."
    }


if __name__ == "__main__":

    result = get_recovery_status("ZONE_A")

    print("RECOVERY STATUS TEST")
    print("=" * 50)

    if result["success"]:

        recovery = result["recovery"]
        lifecycle = result["event_lifecycle"]

        print("Zone:", result["zone_id"])

        print(
            "Recovery detected:",
            recovery.get("recovery_detected")
        )

        print(
            "Recovery level:",
            recovery.get("recovery_level")
        )

        print(
            "Signals recovering:",
            recovery.get("signals_recovering")
        )

        print(
            "Lifecycle stage:",
            lifecycle.get("lifecycle_stage")
        )

        print(
            "Event active:",
            lifecycle.get("event_active")
        )

        print(
            "Recovery active:",
            lifecycle.get("recovery_active")
        )

    else:
        print("ERROR:", result["error"])